spring.application.name=api

# --- Database CONFIG ---
spring.datasource.url=jdbc:mariadb://localhost:3306/fynema
spring.datasource.username=fynema_user
spring.datasource.password=fynema_password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- JWT CONFIG ---
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=3600000

# --- Jackett CONFIG ---
jackett.api.url=http://localhost:9117
jackett.api.key=${JACKETT_API_KEY}

# --- The Movie Database (TMDb) CONFIG ---
tmdb.api.key=${TMDB_API_KEY}