spring.application.name=api

spring.datasource.url=jdbc:mariadb://localhost:3306/fynema
spring.datasource.username=fynema_user
spring.datasource.password=fynema_password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
